#!/usr/bin/env python3
#

import argparse
import os
import pprint
from collections import defaultdict, Counter


parser = argparse.ArgumentParser(description="Generate help for Sarlaccpit (hangman)")
parser.add_argument('-g', '--guess', action='append', help='specify the letter of the next guess')
parser.add_argument('-n', '--number', action='store', help='the number of Sarlacc Pit games played', default=0)
parser.add_argument('-v', '--verbose', action='count', help='increase output verbosity', default=0)
args = parser.parse_args()

print('Enter your solution:')
solution = input().upper()
if args.guess:
    guesses = [c.upper() for c in args.guess]
else:
    guesses = []
poll_num = len(guesses) + 1;
letter_counts = dict(sorted(Counter(solution).items()))

wordlist = solution.split();
wordcount = len(wordlist)
wordword = 'word' if wordcount==1 else 'words'
characteristics = f'This is a phrase with {wordcount} {wordword} of'
ii = 0
for word in wordlist:
    if ii > 0:
        characteristics += ','
    if ii == wordcount - 1 and wordcount > 1:
        characteristics += ' &'
    characteristics += f' {len(word)}'
    ii += 1
if wordcount == 1:
    characteristics += ' letters.'
else:
    characteristics += ' letters, respectively.'

print (f'=============   INTERNAL TEXT FOR GAME MASTER    ==========')
for letter, num in letter_counts.items():
    num = letter_counts[letter];
    if letter in guesses:
        which_poll = guesses.index(letter) + 1
        suffix = f'  GUESSED, poll {which_poll}'
    else:
        suffix = ''
    if letter.isalpha():
        print(f'  {letter}: {num:2}   {suffix}')
print ('')

recent_guess_line = ''
which_poll = 0
if len(guesses) > 0:
    print (f'  Votes so far, by poll:')
    for letter in guesses:
        which_poll+=1
        suffix = f'  CORRECT' if letter in solution else '              INCORRECT'
        print (f' {which_poll:2}     {letter} {suffix}')
    print ('')
    recent_guess_line = f"The chosen letter in poll {which_poll} is the letter '{letter}'. "
    if letter in solution:
        if letter_counts[letter] == 1:
            recent_guess_line += f'There is 1 {letter}.'
        else:
            recent_guess_line += f'There are {letter_counts[letter]} {letter}s.'
    else:
        recent_guess_line += f'There are no {letter}s.'
    wrong_votes_line = 'Wrong Votes so far:';
    wrong_count = 0
    for letter in guesses:
        if letter not in solution:
            wrong_votes_line = wrong_votes_line + f' {letter}'
            wrong_count += 1
    if wrong_count == 0:
        wrong_votes_line += ' None'

print (f'=============  EXTERNAL TEXT FOR POSTING ONLINE  ==========')
print ('')
print ('')
print (f'Welcome to poll number {poll_num} of #SarlaccPit, a Star Wars themed word-guessing game.')
if int(args.number) > 0:
    print (f'This is game number {args.number}, making this #SarlaccPit{args.number}.')
print ('')
print (characteristics)
print ('')
if len(recent_guess_line) > 0:
    print (recent_guess_line)
    print ('')
print ('Solution Board:')
solution_board = ''
for c in solution:
    if c.isalpha():
        if c in guesses:
            solution_board = solution_board + f' {c}';
        else:
            solution_board = solution_board + ' _';
    if c == ' ':
        solution_board = solution_board + ' /';
        if len(solution_board) > 25:
            print (f' {solution_board}');
            solution_board = '';
print (f' {solution_board}');
print ('')
if len(guesses) > 0:
    print (wrong_votes_line)
else:
    print (f'Rules: https://c.im/@darth_hideout/113631196868456567')
print ('')
print ('')
print ('#Games #Puzzles #StarWars')
print ('')
print ('')
